version: '3'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: task_manager
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
